### ISSUE TITLE
Include multiple language labels on narrower concepts

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#19]
By now narrower concepts include labels in one language e.g.

http://coli-conc.gbv.de/services/wikidata/data/?uri=http:%2F%2Fwww.wikidata.org%2Fentity%2FQ223143&language=de,en,es,nl,it,pl,ru,cs,jp

queries via SPARQL

~~~
SELECT DISTINCT ?from ?entity ?entityLabel WHERE {
  VALUES ?from { <http://www.wikidata.org/entity/Q223143> }
  ?entity wdt:P361 | wdt:P31 | wdt:P279 | wdt:P131 <http://www.wikidata.org/entity/Q223143>
  SERVICE wikibase:label { 
    bd:serviceParam wikibase:language "de,en,es,nl,it,pl,ru,cs,jp".
  }
}
~~~

The SPARQL label service only return one label because this is a quick lookup. To query all languages probably takes more time but this may be neglectable:

~~~
SELECT DISTINCT ?from ?entity ?label WHERE {
  VALUES ?from { <http://www.wikidata.org/entity/Q223143> }
  ?entity wdt:P361 | wdt:P31 | wdt:P279 | wdt:P131 <http://www.wikidata.org/entity/Q223143> .
  ?entity rdfs:label ?label .
  FILTER(REGEX(LANG(?label),"^(de|en|es|nl|it|pl|ru|cs|jp)$"))
}
~~~

**Comment by stefandesu** [comment]
Here's an extreme example with 75 narrower concepts: http://coli-conc.gbv.de/services/wikidata/data/?uri=http://www.wikidata.org/entity/Q7868&language=de,en,es,nl,it,pl,ru,cs,jp

This could be used to test the performance when querying all languages instead of using the quick lookup.
