### ISSUE TITLE
Add status endpoint

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#26]
See discussion at https://github.com/gbv/cocoda/issues/293 what is expected to be returned: https://github.com/gbv/cocoda/blob/f7000f0a61525fe3dad0d663287d1520131af5e6/config/cocoda.default.json#L51-L90

**Comment by stefandesu** [comment]
Implemented by necessity in `write-mappings` branch for write access to Wikidata mappings. Closing this issue already even though it is not merged yet.
