### ISSUE TITLE
Additional API endpoints

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#28]
To align with jskos-server:

* [x] [/status](https://github.com/gbv/jskos-server#status) (see #26)
* [x] [/mappings/:_id](https://github.com/gbv/jskos-server#mappings_id) where `:_id` is the mapping statement UUID
* [ ] [/voc](https://github.com/gbv/jskos-server#voc) (see #25, requires wdtaxonomy)
* [ ] [/data](https://github.com/gbv/jskos-server#data) (alias for `/concept`)
* [ ] [/narrower](https://github.com/gbv/jskos-server#narrower)
* [ ] [/ancestors](https://github.com/gbv/jskos-server#ancestors)
* [ ] [/search](https://github.com/gbv/jskos-server#search)
* [ ] occurrences (see #9, needs discussion)

**Comment by stefandesu** [comment]
Previous thoughts (German): https://github.com/gbv/cocoda/wiki/Eintragung-von-Wikidata-Mappings

**Comment by stefandesu** [comment]
The first two points were implemented by necessity for writing access to mappings (still on a separate branch).

**Comment by nichtich** [comment]
I created individual issues for the remaining endpoints
