### ISSUE TITLE
Rename /concept to /data?

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#42]
Or add as alias to better align with JSKOS API

**Comment by stefandesu** [comment]
Yeah, I've been wondering about this as well. As far as I see it, in JSKOS API we have:
- `/data` to query information about one or more concepts or concept schemes.
- `/voc/concepts` to query a list of concepts for a concept scheme.

The former was called `/data` to be aligned with [DANTE](https://api.dante.gbv.de), the latter might not make much sense for Wikidata.

**Comment by nichtich** [comment]
So move `/concept` to `/data` and keep the former as alias.

**Comment by stefandesu** [comment]
Sounds reasonable.
