### ISSUE TITLE
Fix writing of RVK mappings

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#44]
Writing RVK mappings is not possible if the RVK notations contains spaces. Maybe this depends on Wikidata settings, see <https://www.wikidata.org/wiki/Property_talk:P1150#Why_.22string.22.3F> and <https://www.wikidata.org/wiki/Wikidata_talk:Identifier_migration>.

**Comment by stefandesu** [comment]
I think this fails because the `uriPattern` for RVK does not represent a URI with properly encoded notation. Current `uriPattern` is:

```
^http://rvk\\.uni-regensburg\\.de/nt/((LD,)?[A-Z]([A-Z](%20[0-9]+([a-z]|\\.[0-9]+)?( [A-Z][0-9]*)?)?)?( - [A-Z]([A-Z]( [0-9]+([a-z]|\\.[0-9]+)?( [A-Z][0-9]*)?)?)?)?)$
```

**Comment by stefandesu** [comment]
It's [this piece of code](https://github.com/gbv/wikidata-jskos/blob/9768b07b8c6f1d299e1d86496729f127fed36530/lib/queries/get-mapping-schemes.js#L61-L65) that isn't working correctly. JavaScript's String.replace only replaces the first occurrences in the string. I will try to adjust it and see if it works then.

**Comment by stefandesu** [comment]
[Works](https://github.com/gbv/wikidata-jskos/blob/18954496a066c00e6305652d6a4869217badaa95/lib/queries/get-mapping-schemes.js#L62). 👍
