### ISSUE TITLE
Allow multiple concept URIs for /mappings from/to

### ISSUE THREAD

**Issue by stefandesu** [gbv/wikidata-jskos#45]

**Comment by nichtich** [comment]
This is doable, e.g. [getEntities](https://github.com/gbv/wikidata-jskos/blob/master/lib/queries/get-mappings-from.js#L24) supports multiple Q-ids and the SPARQL query for reverse direction can also be extended.

**Comment by stefandesu** [comment]
Note that this has to be implemented in both `lib/queries/get-mappings-from.js` and `lib/queries/get-mappings-to.js`.

**Comment by stefandesu** [comment]
Seems to work well!
