### ISSUE TITLE
/mappings doesn't return mappings for specific STW URIs

### ISSUE THREAD

**Issue by stefandesu** [gbv/wikidata-jskos#46]
#45 seems to have introduced a bug. Consider this query on our currently deployed instance:

https://coli-conc.gbv.de/services/wikidata/mappings?to=http://zbw.eu/stw/descriptor/19664-4

-> It returns one mapping.

Now run the current wikidata-jskos dev locally and try the same:

http://localhost:2013/mappings?to=http://zbw.eu/stw/descriptor/19664-4

-> No mappings.

**Comment by nichtich** [comment]
Fixed with <https://github.com/gbv/wikidata-jskos/commit/8d12163714905552d0faa47eb728934da2342a24>
