### ISSUE TITLE
Include concept coordinates

### ISSUE THREAD

**Issue by nichtich** [gbv/wikidata-jskos#55]
Geographica coordinates should be included in as [`location`](https://gbv.github.io/jskos/jskos.html#location).

**Comment by nichtich** [comment]
Sorry, this issue was opened in the wrong repository. Here it is solved by https://github.com/gbv/wikidata-jskos/commit/623178f7569167de6c612acedd46d6b27d84950f

**Comment by stefandesu** [comment]
As reasoned [here](https://github.com/gbv/jskos-server/issues/88#issuecomment-595561722), I would suggest keeping to GeoJSON specification and providing coordinates in the order 
longitude, latitude.
