### ISSUE TITLE
"loadMappingSchemes" test takes a very long time, causing Travis builds to fail

### ISSUE THREAD

**Issue by stefandesu** [gbv/wikidata-jskos#56]
I had to restart [the latest build on Travis](https://travis-ci.com/gbv/wikidata-jskos/jobs/293817151) two times until it finally succeeded within the 30000ms time limit. "loadMappingSchemes" took 24130ms. I think we should try to eliminate this possible point of failure for Travis builds.

**Comment by nichtich** [comment]
The list of concept schemes could be put in a cache, distributed as part of wikidata-jskos for convenience and updatable on request. The information does not change frequently.
