### ISSUE TITLE
What's up with the dev branch?

### ISSUE THREAD

**Issue by stefandesu** [gbv/wikidata-jskos#62]
@nichtich, a while ago you apparently worked on the `dev` branch, but then ignored that and continued working on `master`. Now, the two branches are split off far enough that there will be a bunch of merge conflicts of you try to merge either way. How do we deal with this? I would like to establish here as well that we only work on `dev` (or in a feature branch that is merged onto `dev`) and then merge with `master` as soon as there's a release.

**Comment by nichtich** [comment]
See <https://github.com/gbv/wikidata-jskos/compare/master...dev> for commits.

**Comment by stefandesu** [comment]
Does this mean we are abondoning the `dev` branch in this repository? If yes, the branch should be removed. If no, the branch should be realigned with the master branch (forced if necessary) and we should, as we do with most other repos, work primarily on the `dev` branch.
