### ISSUE TITLE
Return English prefLabel in addition to the German one

### ISSUE THREAD

**Issue by stefandesu** [gbv/wikidata-jskos#7]
Or all available prefLabels in Wikidata. This might be a bug. Example: http://coli-conc.gbv.de/services/wikidata/concept?uri=http://www.wikidata.org/entity/Q17444426 returns `"prefLabel":{"-":"?"}` while https://www.wikidata.org/wiki/Q17444426 shows English and French labels.

**Comment by nichtich** [comment]
Now implemented with parameter `language` or `languages`: http://coli-conc.gbv.de/services/wikidata/concept?uri=http://www.wikidata.org/entity/Q17444426&languages=en,de

**Comment by nichtich** [comment]
Well, now it's English only - language parameter does not work yet.

**Comment by nichtich** [comment]
The Wikidata has no German label but it works for French and English: http://coli-conc.gbv.de/services/wikidata/data/?uri=http:%2F%2Fwww.wikidata.org%2Fentity%2FQ17444426&language=en,fr
